language: java
jdk:
  - openjdk8

branches: # (1)
  only:
    - master

before_install:
  - chmod +x gradlew


# CI 실행 완료 시 메일로 알람
notifications: # (4)
  email:
    recipients:
      - psh706@hanmail.net